### ISSUE TITLE
indexOf return type

### ISSUE THREAD

**Issue by mernst** [gyhughes/checker-framework#17]
The return type of indexOf should be inferred to be @IndexOrLow.

For a test case, see file `checker/tests/index/index-introduction/IndexOf.java`

**Comment by jsantino** [comment]
This already worked with indexOf(char c) but not with indexOf(string s) due to the TreeUtils.getMethod not resolving overloading. so it only handled the first 1 parameter method. fixing overloading is a TODO in the TreeUtils file. I have for now covered this case by seeing if the method name explicitly ends with the string "indexOf". this may be unsound in the case of user created indexOf with different behaviour; and should be addressed when treeutils.getMethod is updated.
